### ISSUE TITLE
Upload on macOS app doesn't work. WORKAROUND INSIDE

### ISSUE THREAD

**Issue by KrisDavie** [aertslab/SCope#161]
For some reason, when opening the app via finder, the upload breaks. Most likely an environment variable/path issue.

Workaround 1:
Copy looms directly to the loom folder (accessible from the menu bar) and refresh the page (F5/cmd+R)

Workaround 2:
Launch the app via the terminal with the following path: `SCope.app/contents/MacOS/scope`

**Comment by MaybeJustJames** [comment]
@KrisDavie can this be closed?
