### ISSUE TITLE
"Open Loom Folder" option broken in OSX app

### ISSUE THREAD

**Issue by RoganGrant** [aertslab/SCope#164]
File --> Open Loom Folder immediately yields a JavaScript error

Running on MAC OS 10.13.6 (17G65)
SCope version 1.2.0

Error message:

> Uncaught Exception:
> TypeError: Error processing argument at index 0, conversion failure from undefined
>     at glob (/Applications/SCope.app/Contents/Resources/app/index.js:335:30)
>     at f (/Applications/SCope.app/Contents/Resources/app/node_modules/once/once.js:25:25)
>     at Glob.<anonymous> (/Applications/SCope.app/Contents/Resources/app/node_modules/glob/glob.js:151:7)
>     at emitOne (events.js:115:13)
>     at Glob.emit (events.js:210:7)
>     at Glob._finish (/Applications/SCope.app/Contents/Resources/app/node_modules/glob/glob.js:197:8)
>     at done (/Applications/SCope.app/Contents/Resources/app/node_modules/glob/glob.js:182:14)
>     at Glob._processReaddir2 (/Applications/SCope.app/Contents/Resources/app/node_modules/glob/glob.js:379:12)

    at /Applications/SCope.app/Contents/Resources/app/node_modules/glob/glob.js:371:17
    at RES (/Applications/SCope.app/Contents/Resources/app/node_modules/inflight/inflight.js:31:16)

**Comment by KrisDavie** [comment]
Hmm, this is unusual. That folder should have been generated as soon as the app started. 

Could you run this in a terminal `ls -la ~/Library/Application\ Support/scope/my-looms` and post the output?

Thanks

**Comment by RoganGrant** [comment]
I just get
``
ls: /Users/[user]/Library/Application Support/scope/my-looms: No such file or directory
``
Should I create the directory manually?

**Comment by KrisDavie** [comment]
Yeah that's definitely worth a try, although it might not work, because there should be another folder in there, created when the server starts.

Do you see anything in the app when it opens? I.e. the SCope homepage or just a white screen?

Also, are you using a Case-Sensitive volume?

**Comment by RoganGrant** [comment]
Yeah, unfortunately that did not help.

When the app opens it doesn't even create a window (but it is definitely running).

My disk is formatted in APFS, but it is not case-sensitive.

If it helps, I also get a JavaScript error when quitting the app normally:
```
Uncaught Exception:
TypeError: Cannot read property 'stop' of null
    at SCope.stop (/Applications/SCope.app/Contents/Resources/app/index.js:294:15)
    at emitOne (events.js:120:20)
    at App.emit (events.js:210:7)
```

**Comment by KrisDavie** [comment]
Ok, seems like the actual S Python SCope server is not starting, which is resulting in the folders not being created and therefore everything else not working and giving you the errors. This is the latest release?

**Comment by RoganGrant** [comment]
Looks like node.js wasn't installed. The program at least draws a window on open now.

Terminal output seems normal? (ASCII art removed)
``
/Applications/SCope.app/Contents/Resources/app/opt/scopeserver/dataserver/dist/__init__/__init__
SCope Server Packaged.
9081 50952 50953
        
Running SCope Server in production mode...

{"msg": {"origin": "PServer", "value": "SIGSTART"}}

PServer is on!
Starting DataFileHandler...
Starting LoomFileHandler...

{"msg": {"origin": "GServer", "value": "SIGSTART"}}

GServer is on!
Bind Server can start now...
Starting the Bind Server...
Bind Server has started.
``

But both errors still persist

**Comment by KrisDavie** [comment]
Ok, we're getting somewhere. Does the window have anything in it? A first startuo should look something like this:

![image](https://user-images.githubusercontent.com/5079892/44275220-6887b480-a244-11e8-9aac-e9113539e6c4.png)


Can you delete the ~/Library/Application\ Support/scope folder and try to restart? (I don't think this should cause an issue, but just to check)

**Comment by RoganGrant** [comment]
The window I get is very bare-bones, and definitely isn't getting constructed correctly:
<img width="1552" alt="screen shot 2018-08-17 at 10 40 21 am" src="https://user-images.githubusercontent.com/16767040/44275356-204ba080-a20a-11e8-9981-e1f3879bd214.png">

Removing that directory didn't cause any issues. It re-populated on launch, but no change, otherwise.

**Comment by RoganGrant** [comment]
When running from the command line, the ports seem to be correct:
`9081 50951 50952`

As for the output, still seems okay?:
```
rogangrant         610   0.0  0.0  4267752    888 s001  S+   10:14AM   0:00.00 grep scopeserver
rogangrant         585   0.0  0.8  4608804 130376 s000  S+   10:14AM   0:01.40 /Applications/SCope.app/Contents/Resources/app/opt/scopeserver/dataserver/dist/__init__/__init__ -g_port 50951 -p_port 50952 -x_port 9081 --app_mode
```

**Comment by KrisDavie** [comment]
Damn, based on your previous output, I really thought that was the issue. These is one more bit to check these ports if you don't mind?

Applications in macOS are basically just packaged folders, if you enter that folder (right click -> Show Package Contents), you should be able to go SCope.app -> Contents -> Resources -> App. There you should find an index.js, on line 301 you will see `devTools:false`, change that to `devTools:true` and launch SCope once more. You will have the developer tools window open now. If you are on the 'Elements' tab, expand the head tags in the html source and look for three meta tags which will tell us the ports that the frontend is actually using. 

![image](https://user-images.githubusercontent.com/5079892/44385804-d5d76600-a520-11e8-9aea-dadb70a2faf4.png)

Sorry for the hoops to get devTools up, there is a menu option, but it doesn't seem to work.

**Comment by RoganGrant** [comment]
No worries at all! I appreciate the help. What I see is exactly identical. 

In any case, I think I found the issue: I had the stable/recommended version of node.js, (8.11.4) and it appears that SCope requires the current version (10.9.0). My fault entirely. Still, you may want to make that more explicit on the requirements page on GitHub.

Thanks for all of your help!
