### ISSUE TITLE
Error when using "Open Loom Folder" macOS

### ISSUE THREAD

**Issue by mdurante1** [aertslab/SCope#189]
Hi,

I have installed SCope on MacOS version 10.13.6 (17G4015) and when running the app I seem to get the error below when trying to open a loom folder.

I have followed the instructions on the GitHub page for the setup of the miniconda environment, install of SCope, and and app packaging. Additionally, I have have NodeJs Version 10.13.0-h0a44026_0.

It seems as if someone else had an issue with the "open loom folder" function but it was related to an older version of NodeJS. Any ideas on what could be going wrong is greatly appreciated.

Best,
Michael

```
Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from undefined
    at click (/Users/michaeldurante/Documents/GitHub/SCope/release/SCope-darwin-x64/SCope.app/Contents/Resources/app/index.js:366:30)
    at MenuItem.click (/Users/michaeldurante/Documents/GitHub/SCope/release/SCope-darwin-x64/SCope.app/Contents/Resources/electron.asar/browser/api/menu-item.js:52:9)
    at Function.executeCommand (/Users/michaeldurante/Documents/GitHub/SCope/release/SCope-darwin-x64/SCope.app/Contents/Resources/electron.asar/browser/api/menu.js:34:15)
```

**Comment by vacekdavid** [comment]
Have you figured this out? Got the same issue.

**Comment by KrisDavie** [comment]
Hey @vacekdavid, the app has unfortunately fallen behind in the development of SCope and is a low priority at the moment.

However, you should be able to find the loom folder here: `~/Library/Application Support/SCope/my-looms/SCopeApp__<UUID>/`

Putting looms there and refreshing the app should make them appear if the app is working. 

Your other option is a local install of SCope which is pretty simple if you use a conda/miniconda environment. Just make sure to install nodejs >=10 and Python >=3.7 in the environment, follow the instructions in the readme and then you should be able to just ruin `npm run scope`

**Comment by vacekdavid** [comment]
Thank you for your help! No folder named SCope is created in Application Support when I download the standalone app. I will give the conda environment a go.
