### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by sedjro** [aertslab/SCope#200]
Hi,

We have two versions of SCope installed; one is in local and another in a web server.
We would like to change the home page of SCope to add the description of the loom file for our own version of Scope.
We found the file "Welcome.jsx" corresponding to the home page and we have modified it. 
These modifications are displayed on the local SCope.
But on the web server version, the modifications are not taking into account.
Do you have any idea of why there is this difference?  

Best,
Yannick

**Comment by KrisDavie** [comment]
Solved outside of GitHub. Changes require `npm run build` to be run to be incorporated correctly.
