### ISSUE TITLE
loom file does not show

### ISSUE THREAD

**Issue by KatjaRM** [aertslab/SCope#201]
Hi!

I am trying to convert a Seurat file into a loom file that I can use to view in Scope. I am not getting error messages when converting the file in Seurat, so I am posting this question here instead of to the Seurat developers. Hope that's okay.

I am working with Seurat v3.0 and convert my object to loom with as.loom and below is how it looks like. When I am uploading the file into Scope at [http://scope.aertslab.org](url) I can not see any cells in the plot and it remains empty, although the file is shown as uploaded. Are there any essential layers or attributes missing? Do you have any idea how to add them to get it to work?

Thanks for looking into this!!!

Katja

as.loom(CF2,` assay = NULL, filename = file.path(getwd(), paste0(Project(object = CF2), ".loom")), max.size = "400mb", chunk.dims = NULL, chunk.size = NULL, overwrite = FALSE, verbose = TRUE)

Transposing input data: loom file will show input columns (cells) as rows and input rows (features) as columns
This is to maintain compatibility with other loom tools
  |=================================================================================| 100%
Adding: CellID
Adding: Gene
Adding a layer to norm_data (layer 1 of 1)
  |=================================================================================| 100%
Adding: Selected
Adding: nGene
Adding: nUMI
Adding: orig_ident
Adding: percent_mito
Adding: res_0_1
Adding: finalcluster
Adding: nCount_RNA
Adding: nFeature_RNA
Adding: RNA_snn_res_1
Adding: seurat_clusters
Adding: ClusterID
Adding: ClusterName
No scaled data present, not adding scaled data, dimensional reduction information, or neighbor graphs
Class: loom
Filename: /Users/katja/10x Nystul filtered.loom
Access type: H5F_ACC_RDWR
Attributes: version, chunks, LOOM_SPEC_VERSION, assay, last_modified
Listing:
       name    obj_type dataset.dims dataset.type_class
  col_attrs   H5I_GROUP         <NA>               <NA>
 col_graphs   H5I_GROUP         <NA>               <NA>
     layers   H5I_GROUP         <NA>               <NA>
     matrix H5I_DATASET 10607 x 9623          H5T_FLOAT
  row_attrs   H5I_GROUP         <NA>               <NA>
 row_graphs   H5I_GROUP         <NA>               <NA>

**Comment by KrisDavie** [comment]
Hey Katja!

Thanks for your interest in scope. 

SCope needs some kind of dimensionality reduction (PCa/tSNE/UMAP) to display points, you can see from your Seurat output that it is not adding dimensionality data to the loom file from this line of your output:

> No scaled data present, not adding scaled data, dimensional reduction information, or neighbor graphs

The description from the Seurat package seems to imply that the scaled data slot needs to be present for those to be added automatically ([see here](https://github.com/satijalab/seurat/blob/25b830b0dd6f12538516f0faf9a3b3ddfd0ce6d8/R/objects.R#L1236)), maybe you can try that and give it another go?

Alternatively, you could add them yourself usinng loomR/[SCopeLoomR](https://github.com/aertslab/SCopeLoomR), following the details in the [SCope wiki](https://github.com/aertslab/SCope/wiki/Data-Format) for how we load the embeddings.

Hopefully this helps you get your data visualized!

Kris

**Comment by KatjaRM** [comment]
Hi Kris,

Thank you so much! I will try this out.

Best,

Katja

**Comment by KatjaRM** [comment]
Hi Kris,

Thank you so much! I will try this out.

Best,

Katja

**Comment by KatjaRM** [comment]
Hi Kris,

After following you recommendation I was finally able to create a loom file that was compatible with SCope. Thanks a ton, this was really helpful!

One thing that I realized while trying to add Seurat clustering is, that it appears that there is an issue with the change of the Seurat object structure from v2 to v3. SCopeLoomR requires the slot "data" which is saved in different levels in Seurat v2 and v3. I can circumvent the error message I get 

> Error in is.data.frame(x) : 
  no slot of name "data" for this object of class "Seurat"

by directly assessing data via seurat@assays$RNA, which works. But then the next issue that I have is that "calc.params" is required, which apparently is not stored anymore in v3 Seurat objects. See here:
[https://github.com/satijalab/seurat/issues/1576](url)

I can get clustering information from a v2 Seurat object, but the table returned by `get_clusterings(loom)` does not look right, so I am wondering if there is a way to get clustering information from v3 Objects?

Best wishes and thank you so much for your help!

Katja

**Comment by mase5** [comment]
Hi @KatjaRM ,

Unfortunately, SCopeLoomR is not compatible with Seurat v3 yet.
I will add a helper function to add the clusterings from Seurat v3.

Will be back to you once this is done

**Comment by KatjaRM** [comment]
Hi @mase5,

I would be happy to hear from you whenever you add it. Thank you for working on it!

Best,

Katja

**Comment by mase5** [comment]
Hi @KatjaRM,

I've updated SCopeLoomR package. Now in SCopeLoomR version 0.5.0, the function `add_seurat_clustering` should now be compatible with Seurat v3 objects hence clustering information should be visible in SCope.

Max

**Comment by KatjaRM** [comment]
Hi Max!

Thank you for implementing this! I have yet to try the function out but and had been hoping to give you feedback but my schedule did not allow it yet. I will close the issue, though :)
Again, thank you very much for your kind help!

Best,

Katja
