### ISSUE TITLE
Not able to load new files

### ISSUE THREAD

**Issue by prete** [aertslab/SCope#220]
Hi, I'm trying to load a new file but can't seem to be able to. I've tried the online version and on my local without any luck. May be there is something wrong with the format of my file? Any pointers?

[csc_embryo2m_5k.loom.zip](https://github.com/aertslab/SCope/files/3875986/csc_embryo2m_5k.loom.zip)

**Comment by dweemx** [comment]
Hi @prete,

It seems this loom file does not follow the loom convention from loompy (http://linnarssonlab.org/loompy/conventions/index.html).

SCope requires the `Gene` row attribute to exist.
The loom file attached has been fixed (I created a `Gene` row attribute which is a copy of `gene_short_name` row attribute).

The website ([scope.aertslab.org](url)) would need to be updated; 
This will be done tomorrow. 
(We will let you know when it's done)

[csc_embryo2m_5k_fixed.loom.zip](https://github.com/aertslab/SCope/files/3876309/csc_embryo2m_5k_fixed.loom.zip)

**Comment by dweemx** [comment]
Hi @prete,

scope.aertslab.org has been updated; so If you use the file in my previous post, you should be able to visualize it.

**Comment by prete** [comment]
Thank you! 

I've used this as a quick way for converting h5ad files to loom.
```python
import scanpy as sc
adata = sc.read('input_file.h5ad')
adata.var['Gene'] = adata.var['gene_short_name']
adata.write_loom('output_file.loom', True)
```

Follow up question: have you tried loading more than 1 million cells? Is there any suggested way to optimize the loading process?

**Comment by dweemx** [comment]
We haven't tried yet to load a big dataset like that but this a work in progress.
Also If you have any suggestion/feature that you'd like to see, please feel free to tell us by sending us an email or posting a GitHub issue.

**Comment by dweemx** [comment]
I'm closing this issue, since the bug has been solved
