### ISSUE TITLE
Dependencies fail to build under Python 3.8.1

### ISSUE THREAD

**Issue by jhc-at-home** [aertslab/SCope#232]
```bash
cd opt/
pipenv --python 3.8
pipenv install -e .
```
`pyarrow` fails to build

**Comment by KrisDavie** [comment]
Known issue in pyarrow: https://github.com/apache/arrow/issues/5987

Release 0.16.0 should fix this, commit history on github seems to indicate it is out, but not yet available on pypi.

**Comment by KrisDavie** [comment]
Pyarrow has been updated to have 3.8+ compatibility: https://pypi.org/project/pyarrow/
