### ISSUE TITLE
CPM is not CPM

### ISSUE THREAD

**Issue by KrisDavie** [aertslab/SCope#277]
The CPM normalisation is just normalizing by library size, not multiplying values by 1,000,000

**Comment by KrisDavie** [comment]
After some local testing, it is a trivial, single line fix. 

However, due to the way we handle the colour scales, particularly when values are log + cpm normalised, the distribution shifts to having all values at the higher end. The colour is still scaled between 0 and max(vals)

Pre correct CPM (no x1000000)
![image](https://user-images.githubusercontent.com/5079892/76426228-0f91eb00-63ab-11ea-96d6-b6c3bed3215f.png)

Post correct CPM
![image](https://user-images.githubusercontent.com/5079892/76426271-20daf780-63ab-11ea-8ad1-f8c7a2074df7.png)

This ends up with the colour being biased to the right (higher values), but the colour is still scaled from 0. Implementing a lower bound on the colour bar would help fix this, but is a lot more work

**Comment by dweemx** [comment]
We should at least rename it to library size normalization instead of CPM then no ?
