### ISSUE TITLE
Define data that may be stored in a database and/or on the filesystem

### ISSUE THREAD

**Issue by MaybeJustJames** [aertslab/SCope#284]
* Observe current data and metadata
* Imagine future features and their required (meta)data
* Consider how these data are/could be used, queried, updated
* Propose which data may be stored in a database, and which should be stored elsewhere (list where)

**Comment by KrisDavie** [comment]
https://docs.google.com/document/d/1tCk5AK35unQUmG4TMACRaGYT4Kb2wiRrtHD5uvZSCu4/edit?usp=sharing

This document gives some overview of what should be needed. Comments welcome

**Comment by MaybeJustJames** [comment]
@KrisDavie could this be exported to MD and put in the `docs/` directory please? In a PR I would ask for more details
