### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by ChenchenWangiSummer** [aertslab/SCope#366]
Hi,

Unfortunately I can't get SCope app to work in MacOS, I installed SCope_macOS_x64_v1.3.5_CI. When I open the app and clicked "open loom folder", "A JavaScript error occurred in the main process" showed as:
Uncaught Exception:
TypeError: Cannot read property 'stop' of null
    at SCope.stop (/Applications/SCope.app/Contents/Resources/app/index.js:318:15)
    at emitOne (events.js:120:20)
    at App.emit (events.js:210:7)

So, what happened and how to solve this problem?
Thanks very much!
CC

**Comment by KrisDavie** [comment]
HI CC,

Unfortunately, the development of the app has fallen behind due to recent changes. Someone else had a similar issue here (https://github.com/aertslab/SCope/issues/189#issuecomment-648720348) could you try those instructions and let me know if it works?

Many thanks,

Kris
