### ISSUE TITLE
what is the exact mean of superposition?

### ISSUE THREAD

**Issue by sygongcode** [aertslab/SCope#368]
Hello, everyone,

First, thank you for your nice work that helps me a lot with my project.

I have some questions when I using SCope to search for some genes' alteration in the fly brain in aging. I didn't find any contact information for help. So, I come here to ask for help.
The question is that when I use the compare part, I found three options, Number of displays, Superposition(N/A, OR, AND), and Configuration, what is the exact mean of superposition? For example, If I drag age 3, and age 15, age 30 and age 50 in genotype W1118, male fly brain for comparison. And then I type a gene that I am interested in. after I select OR or AND in the superposition option, I got different plots. So, what are the exact means when I select OR or AND? Can anyone help me? Thank you.

Best regards,

Shangyu

**Comment by dweemx** [comment]
Hey @sygongcode ,
Superposition is a feature that is applying a logical operator (like in computer science) on the different set of cells from the annotation values that you have dragged onto a viewer. As an example, in your case, 
- Superposition(OR) with age `3`, `15`, `30`,  `50` and genotype `W1118` will display all the cells that have at least one of these annotations.
- Superposition(AND) with age `3`, `15`, `30`,  `50` and genotype `W1118`: will display you only the cells that have all these 5 annotations.

**Comment by sygongcode** [comment]
> Hey @sygongcode ,
> Superposition is a feature that is applying a logical operator (like in computer science) on the different set of cells from the annotation values that you have dragged onto a viewer. As an example, in your case,
> 
> * Superposition(OR) with age `3`, `15`, `30`,  `50` and genotype `W1118` will display all the cells that have at least one of these annotations.
> * Superposition(AND) with age `3`, `15`, `30`,  `50` and genotype `W1118`: will display you only the cells that have all these 5 annotations.

Thank you so much. Now I can confirm it. 

Why I ask this question, is because I found some strange results. But maybe it is what it is. So, thank you again.

Best regards,
Shangyu
