### ISSUE TITLE
Local container installation: Failed to load gRPC binary module

### ISSUE THREAD

**Issue by asoete** [aertslab/SCope#400]
Dear

I'm running into some issues when trying to install SCope locally via the docker setup.

Some remarks before I post the steps I took:
* We want to reverse proxy from the host using nginx
* We are using podman instead of docker, so we can easily run the container without needing to run a daemon with root privileges.
* I have not passed any storage configuration options. I postponed this until I have the container running...

Steps to build the local assets and image:
```
git clone https://github.com/aertslab/SCope.git
cd SCope
git checkout 63b96e2d4f96d37b05527e0cd52c39fc652a995e
vim config.json
scl enable rh-nodejs12 -- npm install
scl enable rh-nodejs12 -- npm run build
podman build --tag scope_63b96e2 -f Dockerfile
```
Runningthe container, unfortunately produces an error"
```
podman run -it --rm  --expose 8000 --expose 55850-55853 --publish 127.0.0.1:8000:8000 --publish 127.0.0.1:55850-55853:55850-55853 scope_63b96e2 "poetry" "run" "hypercorn" "--bind" "0.0.0.0" "main:scope_api"
```
> ```
> 2020-11-16 16:49:16,012 - scopeserver - INFO - 
>   /$$$$$$   /$$$$$$                                       /$$$$$$
>  /$$__  $$ /$$__  $$                                     /$$__  $$
> | $$  \__/| $$  \__/  /$$$$$$   /$$$$$$   /$$$$$$       | $$  \__/  /$$$$$$   /$$$$$$  /$$    /$$ /$$$$$$   /$$$$$$
> |  $$$$$$ | $$       /$$__  $$ /$$__  $$ /$$__  $$      |  $$$$$$  /$$__  $$ /$$__  $$|  $$  /$$//$$__  $$ /$$__  $$
>  \____  $$| $$      | $$  \ $$| $$  \ $$| $$$$$$$$       \____  $$| $$$$$$$$| $$  \__/ \  $$/$$/| $$$$$$$$| $$  \__/
>  /$$  \ $$| $$    $$| $$  | $$| $$  | $$| $$_____/       /$$  \ $$| $$_____/| $$        \  $$$/ | $$_____/| $$
> |  $$$$$$/|  $$$$$$/|  $$$$$$/| $$$$$$$/|  $$$$$$$      |  $$$$$$/|  $$$$$$$| $$         \  $/  |  $$$$$$$| $$
>  \______/  \______/  \______/ | $$____/  \_______/       \______/  \_______/|__/          \_/    \_______/|__/
>                               | $$
>                               | $$
>                               |__/
> 
> 2020-11-16 16:49:16,013 - scopeserver - DEBUG - Starting data server on port 55853. app_mode: False
> 2020-11-16 16:49:16,013 - scopeserver - DEBUG - Starting upload server on port 55851
> 2020-11-16 16:49:16,014 - scopeserver - DEBUG - Starting bind server on port 55852
> Running on 0.0.0.0:8000 over http (CTRL + C to quit)
> {"msg": {"origin": "PServer", "value": "SIGSTART"}}
> 2020-11-16 16:49:16,048 - scopeserver.dataserver.utils.data_file_handler - ERROR - No data folder detected. Making loom data folder: /root/.local/share/SCope/my-looms.
> 2020-11-16 16:49:16,048 - scopeserver.dataserver.utils.data_file_handler - ERROR - No gene-sets folder detected. Making gene-sets data folder in current directory: /root/.local/share/SCope/my-gene-sets.
> 2020-11-16 16:49:16,049 - scopeserver.dataserver.utils.data_file_handler - ERROR - No AUCell rankings folder detected. Making AUCell rankings data folder in current directory: /root/.local/share/SCope/my-aucell-rankings.
> 2020-11-16 16:49:16,049 - scopeserver.dataserver.utils.data_file_handler - ERROR - No Config folder detected. Making Config folder: /root/.config/SCope.
> 2020-11-16 16:49:16,049 - scopeserver.dataserver.utils.data_file_handler - ERROR - No Logs folder detected. Making Logs folder: /root/.cache/SCope/log.
> 2020-11-16 16:49:16,141 - scopeserver.dataserver.utils.data_file_handler - DEBUG - Building UUID "database"
> 2020-11-16 16:49:16,141 - scopeserver.dataserver.utils.data_file_handler - DEBUG - No Existing Permanent Sessions, generating rw App UUID:"
> 2020-11-16 16:49:16,141 - scopeserver.dataserver.utils.data_file_handler - DEBUG -      UUID SCopeApp__225b2d13-f022-4efc-8844-297762828e42, mode rw. Valid until 2021-11-16 16:49:16
> 2020-11-16 16:49:16,142 - scopeserver.dataserver.utils.data_file_handler - DEBUG - Building UUID "database"
> {"msg": {"origin": "GServer", "value": "SIGSTART"}}
> /app/opt/scopeserver/bindserver/node_modules/grpc/src/grpc_extension.js:55
>     throw error;
>     ^
> 
> Error: Failed to load gRPC binary module because it was not installed for the current system
> Expected directory: node-v83-linux-x64-glibc
> Found: [node-v72-linux-x64-glibc]
> This problem can often be fixed by running "npm rebuild" on the current system
> Original error: Cannot find module '/app/opt/scopeserver/bindserver/node_modules/grpc/src/node/extension_binary/node-v83-linux-x64-glibc/grpc_node.node'
> Require stack:
> - /app/opt/scopeserver/bindserver/node_modules/grpc/src/grpc_extension.js
> - /app/opt/scopeserver/bindserver/node_modules/grpc/src/client_interceptors.js
> - /app/opt/scopeserver/bindserver/node_modules/grpc/src/client.js
> - /app/opt/scopeserver/bindserver/node_modules/grpc/index.js
> - /app/opt/scopeserver/bindserver/server.js
>     at Object.<anonymous> (/app/opt/scopeserver/bindserver/node_modules/grpc/src/grpc_extension.js:53:17)
>     at Module._compile (internal/modules/cjs/loader.js:1063:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
>     at Module.load (internal/modules/cjs/loader.js:928:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
>     at Module.require (internal/modules/cjs/loader.js:952:19)
>     at require (internal/modules/cjs/helpers.js:88:18)
>     at Object.<anonymous> (/app/opt/scopeserver/bindserver/node_modules/grpc/src/client_interceptors.js:144:12)
>     at Module._compile (internal/modules/cjs/loader.js:1063:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10) {
>   code: 'MODULE_NOT_FOUND'
> }
> ^C2020-11-16 16:54:53,791 - scopeserver - INFO - Terminating servers...
> 2020-11-16 16:54:53,976 - scopeserver - INFO - Servers successfully terminated. Exiting.
> ```

Do you have any pointers on how to resolve this grpc module error?

Many thanks in advance!

**Comment by dweemx** [comment]
Hi @asoete,

I think these two lines should not be executed:
```
scl enable rh-nodejs12 -- npm install
scl enable rh-nodejs12 -- npm run build
```
This could cause the error you're having. It's probably installing and building SCope with a system node version which probably 
 is different from the one used in the container. I think all the installation should be containerized. Documentation is probably unclear, let me know if this is the case.

I tested the following with success on my local computer
```
git clone https://github.com/aertslab/SCope.git
cd SCope
nano config.json
sudo podman build --tag scope_63b96e2 -f Dockerfile
```

Could you try this and see if this works for you ?

**Comment by asoete** [comment]
Thanks @dweemx for getting back to me this fast.

Just to be clear I (now) built the container from master (1ba9adc92cd88bbae944551a0f163a8ca652bdd5) as I think you suggested in your comment.

When I start the container with:
```
$ podman run -it --rm  --expose 8000 --expose 55850-55853 --publish 127.0.0.1:8000:8000 --publish 127.0.0.1:55850-55853:55850-55853 scope_gh_master "poetry" "run" "hypercorn" "--bind" "0.0.0.0" "main:scope_api"
```
I get:
> ```
> Traceback (most recent call last):
>   File "/root/.cache/pypoetry/virtualenvs/scopeserver-1v7iq-XX-py3.8/bin/hypercorn", line 8, in <module>
>     sys.exit(main())
>   File "/root/.cache/pypoetry/virtualenvs/scopeserver-1v7iq-XX-py3.8/lib/python3.8/site-packages/hypercorn/__main__.py", line 236, in main
>     run(config)
>   File "/root/.cache/pypoetry/virtualenvs/scopeserver-1v7iq-XX-py3.8/lib/python3.8/site-packages/hypercorn/run.py", line 34, in run
>     worker_func(config)
>   File "/root/.cache/pypoetry/virtualenvs/scopeserver-1v7iq-XX-py3.8/lib/python3.8/site-packages/hypercorn/asyncio/run.py", line 158, in asyncio_worker
>     app = load_application(config.application_path)
>   File "/root/.cache/pypoetry/virtualenvs/scopeserver-1v7iq-XX-py3.8/lib/python3.8/site-packages/hypercorn/utils.py", line 89, in load_application
>     module = import_module(import_name)
>   File "/opt/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/app/opt/main.py", line 9, in <module>
>     from scopeserver.config import from_file
>   File "/app/opt/scopeserver/__init__.py", line 19, in <module>
>     import scopeserver.config as configuration
>   File "/app/opt/scopeserver/config.py", line 67, in <module>
>     settings = Settings()
>   File "pydantic/env_settings.py", line 33, in pydantic.env_settings.BaseSettings.__init__
>   File "pydantic/main.py", line 346, in pydantic.main.BaseModel.__init__
> pydantic.error_wrappers.ValidationError: 1 validation error for Settings
> DATABASE_URL
>   field required (type=value_error.missing)
> ```

And with
```
podman run -it --rm  --expose 8000 --expose 55850-55853 --publish 127.0.0.1:8000:8000 --publish 127.0.0.1:55850-55853:55850-55853 scope_gh_master bash /app/start.sh
```
I get:
```
  FAILED: No config file 'alembic.ini' found, or file has no '[alembic]' section
```

So do I need to try the specified steps on another commit? Or do I need another entry command?

Thanks.

**Comment by dweemx** [comment]
The following command works for me:
```
$ sudo podman run \
   -it \
   --rm \
   --expose 8000 \
   --expose 55850-55853 \
   --publish 127.0.0.1:8000:8000 \
   --publish 127.0.0.1:55850-55853:55850-55853 scope_63b96e2 "poetry" "run" "dotenv" "run" "hypercorn" "--bind" "0.0.0.0" "main:scope_api"

2020-11-25 16:35:31,129 - scopeserver - INFO - 
  /$$$$$$   /$$$$$$                                       /$$$$$$
 /$$__  $$ /$$__  $$                                     /$$__  $$
| $$  \__/| $$  \__/  /$$$$$$   /$$$$$$   /$$$$$$       | $$  \__/  /$$$$$$   /$$$$$$  /$$    /$$ /$$$$$$   /$$$$$$
|  $$$$$$ | $$       /$$__  $$ /$$__  $$ /$$__  $$      |  $$$$$$  /$$__  $$ /$$__  $$|  $$  /$$//$$__  $$ /$$__  $$
 \____  $$| $$      | $$  \ $$| $$  \ $$| $$$$$$$$       \____  $$| $$$$$$$$| $$  \__/ \  $$/$$/| $$$$$$$$| $$  \__/
 /$$  \ $$| $$    $$| $$  | $$| $$  | $$| $$_____/       /$$  \ $$| $$_____/| $$        \  $$$/ | $$_____/| $$
|  $$$$$$/|  $$$$$$/|  $$$$$$/| $$$$$$$/|  $$$$$$$      |  $$$$$$/|  $$$$$$$| $$         \  $/  |  $$$$$$$| $$
 \______/  \______/  \______/ | $$____/  \_______/       \______/  \_______/|__/          \_/    \_______/|__/
                              | $$
                              | $$
                              |__/

2020-11-25 16:35:31,129 - scopeserver - DEBUG - Starting data server on port 55853. app_mode: False
2020-11-25 16:35:31,129 - scopeserver - DEBUG - Starting upload server on port 55851
2020-11-25 16:35:31,130 - scopeserver - DEBUG - Starting bind server on port 55852
{"msg": {"origin": "PServer", "value": "SIGSTART"}}
Running on 0.0.0.0:8000 over http (CTRL + C to quit)
2020-11-25 16:35:31,147 - scopeserver.dataserver.utils.data_file_handler - ERROR - No data folder detected. Making loom data folder: /root/.local/share/SCope/my-looms.
2020-11-25 16:35:31,147 - scopeserver.dataserver.utils.data_file_handler - ERROR - No gene-sets folder detected. Making gene-sets data folder in current directory: /root/.local/share/SCope/my-gene-sets.
2020-11-25 16:35:31,147 - scopeserver.dataserver.utils.data_file_handler - ERROR - No AUCell rankings folder detected. Making AUCell rankings data folder in current directory: /root/.local/share/SCope/my-aucell-rankings.
2020-11-25 16:35:31,147 - scopeserver.dataserver.utils.data_file_handler - ERROR - No Config folder detected. Making Config folder: /root/.config/SCope.
2020-11-25 16:35:31,147 - scopeserver.dataserver.utils.data_file_handler - ERROR - No Logs folder detected. Making Logs folder: /root/.cache/SCope/log.
2020-11-25 16:35:31,211 - scopeserver.dataserver.utils.data_file_handler - DEBUG - Building UUID "database"
2020-11-25 16:35:31,211 - scopeserver.dataserver.utils.data_file_handler - DEBUG - No Existing Permanent Sessions, generating rw App UUID:"
2020-11-25 16:35:31,211 - scopeserver.dataserver.utils.data_file_handler - DEBUG -      UUID SCopeApp__ba197a52-6062-4fe4-a518-79bacf796e78, mode rw. Valid until 2021-11-25 16:35:31
2020-11-25 16:35:31,211 - scopeserver.dataserver.utils.data_file_handler - DEBUG - Building UUID "database"
{"msg": {"origin": "GServer", "value": "SIGSTART"}}
```

**Comment by asoete** [comment]
Dear @dweemx 

I finally got around investing some additional time in this.

We got everything up and working but we took a non standard approach as we want to use rootless podman an can't use docker-compose:

1. We used took f3e2fb9 as the commit to work from. As this commit passed your CI/CD pipeline. 
   _master_ currently produces a bunch of typescript errors during the build phase. This is why we went with an "older" commit.

2. Next: use podman to build the SCope container from your Dockerfile. 
   ```
   podman build --tag scope -f Dockerfile
   ```
   And run it via:
   ```
   podman run \
      -it \
      --rm \
      --expose 8000 \
      --expose 55850-55853 \
      --publish 127.0.0.1:8000:8000 \
      --publish 127.0.0.1:55850-55853:55850-55853 scope_black "poetry" "run" "dotenv" "run" "hypercorn" "--bind" "0.0.0.0" "main:scope_api"
   ```

3. This builds and runs correctly but isn't well integrated with the provided reveres-proxy solution. Remember we are not using docker so we can not share volumes between containers as easily as you do with the docker-compose.
   Our workaround for this is to extract the `index.html` and `assets/*` resources from the container to the host and to serve them directly from the host. (We are using nginx as our webserver / proxy).
   ```
   podman cp ${container-id}:/app/index.html /path/to/scope
   podman cp ${container-id}:/app/assets /path/to/scope
   ```

4. Ports 55851-3 are proxied by nginx to the running container.

5. Another issue we had to solve is that we run scope from a sub-path: `example.com/scope`. With some sed magic we where able to update the build artifacts to point to the correct endpoints and set the correct HTTP, webscoket schemes:
   ```
   $ sed -i -e 's|ws://example.com:80|wss://example.com/scope|g' assets/SCope-1.8.2.f3e2fb9.js
   $ sed -i -e 's|http://example.com:80|https://example.com/scope|g' assets/SCope-1.8.2.f3e2fb9.js
   ```

6. Next the SCope server produced the following error:
   ```
   Error: Failed to load gRPC binary module because it was not installed for the current system
   Expected directory: node-v83-linux-x64-glibc
   Found: [node-v64-linux-x64-glibc]
   This problem can often be fixed by running "npm rebuild" on the current system
   ```
   This was solved by attaching to the running SCope container and manually running `npm rebuild` in `/app/opt/scopeserver/bindserver/`

7. Now SCope is loading within the browser but produces the following error:
   ```
   2021-01-20 09:46:52,744 - grpc._server - ERROR - Exception calling application: badly formed hexadecimal UUID string
   Traceback (most recent call last):
     File "/root/.cache/pypoetry/virtualenvs/scopeserver-1v7iq-XX-py3.8/lib/python3.8/site-packages/grpc/_server.py", line 435, in _call_behavior
       response_or_iterator = behavior(argument, context)
     File "/app/opt/scopeserver/dataserver/modules/gserver/GServer.py", line 622, in getRemainingUUIDTime
       uuid.UUID(uid)
     File "/opt/conda/lib/python3.8/uuid.py", line 169, in __init__
       raise ValueError('badly formed hexadecimal UUID string')
   ValueError: badly formed hexadecimal UUID string
   ```
   This is solved / worked around by appending a UUID to the URL on first load and then requesting a new session...


I thought I would post my findings here as it might be interesting for others...

Note: We just have an empty instance running now. Adding data and testing functionality still needs to be done.

Kind regards
