### ISSUE TITLE
Regulon exploration tab not working on web application

### ISSUE THREAD

**Issue by hbandukw** [aertslab/SCope#411]
Hello,

I have been trying to explore my SCENIC results on SCope but the "Regulon" tab is not working as it should. 

When I enter a TF /regulon name, just the gene expression values are displayed (i.e. information is displayed in the bottom right plot). The "AUC distribution", "Regulon AUC values" or the "cells passing thresholds" doesn't display anything. 
I have attached a screen-shot with the fly-adult brain data. I tried this with various datasets uploaded on SCope (including my own dataset) and also tried with different TFs but every time the same thing happens leading me to believe that there is something wrong with the app itself. 

<img width="1471" alt="Screen Shot 2021-01-21 at 5 08 37 PM" src="https://user-images.githubusercontent.com/20444993/105418632-7149f500-5c0b-11eb-9b40-6d0be03dd684.png">

On another note, does the "cells passing thresholds" depend on the "optional binarization" step? Does that need to be explicitly incorporated into the loom file?

Thanks.

**Comment by dweemx** [comment]
Hi @hbandukw,
Unfortunately I cannot reproduce your issue. Here is what I get using Google Chrome
![image](https://user-images.githubusercontent.com/16015936/106464323-cb16ae80-6498-11eb-9dac-4ed1615341ca.png)

Which browser are you using ? Have you also come across this issue on other navigators ?

Sorry for the late response

**Comment by KrisDavie** [comment]
Hi @hbandukw 

There actually was a bug which was present in SCope, but it was fixed last week in commit https://github.com/aertslab/SCope/commit/8af1e3dfc351b18b54a8e9b3b75840b25db1fcdb, the https://scope.aertslab.org/ website is running this version now so everything should work.

As @dweemx said, apologies for the delayed response, it seems I missed the mail in my inbox.

Cheers,

Kris
